import type { BroadcastTheme } from "@/types/broadcast"

const base: Omit<
  BroadcastTheme,
  "id" | "name" | "background" | "verseText" | "reference" | "layout" | "transition" | "textBox"
> = {
  builtin: true,
  pinned: false,
  createdAt: 0,
  updatedAt: 0,
  resolution: { width: 1920, height: 1080 },
  verseNumbers: {
    visible: true,
    fontSize: 16,
    color: "#ffffff",
    superscript: true,
  },
}

// Kairos — minimal, light
const KAIROS: BroadcastTheme = {
  ...base,
  id: "builtin-kairos",
  name: "Kairos",
  background: {
    type: "solid",
    color: "#fafaf9",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "DM Sans Variable",
    fontSize: 64,
    fontWeight: 400,
    color: "#1c1917",
    horizontalAlign: "left",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.6,
    letterSpacing: -0.5,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 14,
    color: "#a8a29e",
    superscript: true,
  },
  reference: {
    fontFamily: "DM Sans Variable",
    fontSize: 32,
    fontWeight: 500,
    color: "#a8a29e",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 3,
    position: "above",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 80, right: 120, bottom: 80, left: 120 },
    textAlign: "left",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 75,
    textAreaHeight: 70,
    referenceGap: 24,
  },
  transition: {
    type: "fade",
    duration: 400,
    easing: "ease-out",
    direction: "up",
  },
}

// Doxa — cinematic, dark, gold
const DOXA: BroadcastTheme = {
  ...base,
  id: "builtin-doxa",
  name: "Doxa",
  background: {
    type: "gradient",
    color: "#0c0a09",
    gradient: {
      type: "radial",
      angle: 0,
      stops: [
        { color: "#1c1917", position: 0 },
        { color: "#0c0a09", position: 100 },
      ],
    },
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Playfair Display Variable",
    fontSize: 72,
    fontWeight: 400,
    color: "#fafaf9",
    horizontalAlign: "center",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.5,
    letterSpacing: 0,
    shadow: { color: "rgba(0,0,0,0.6)", blur: 12, x: 0, y: 4 },
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 18,
    color: "#d4a574",
    superscript: true,
  },
  reference: {
    fontFamily: "DM Sans Variable",
    fontSize: 36,
    fontWeight: 500,
    color: "#d4a574",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 4,
    position: "above",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 80, right: 100, bottom: 80, left: 100 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 80,
    textAreaHeight: 75,
    referenceGap: 32,
  },
  transition: {
    type: "fade",
    duration: 600,
    easing: "ease-in-out",
    direction: "up",
  },
}

// Pneuma — overlay, transparent
const PNEUMA: BroadcastTheme = {
  ...base,
  id: "builtin-pneuma",
  name: "Pneuma",
  background: {
    type: "transparent",
    color: "transparent",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: true,
    color: "#000000",
    opacity: 0.65,
    borderRadius: 12,
    padding: 28,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 56,
    fontWeight: 500,
    color: "#ffffff",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.5,
    letterSpacing: 0,
    shadow: { color: "rgba(0,0,0,0.8)", blur: 6, x: 0, y: 2 },
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 15,
    color: "#fbbf24",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 32,
    fontWeight: 600,
    color: "#fbbf24",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 1,
    position: "below",
  },
  layout: {
    anchor: "bottom-center",
    offsetX: 0,
    offsetY: -40,
    padding: { top: 32, right: 48, bottom: 32, left: 48 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 90,
    textAreaHeight: 35,
    referenceGap: 20,
  },
  transition: {
    type: "fade",
    duration: 300,
    easing: "ease-in-out",
    direction: "up",
  },
}

// Rhema — bold, dark, warm
const RHEMA: BroadcastTheme = {
  ...base,
  id: "builtin-rhema",
  name: "Rhema",
  background: {
    type: "gradient",
    color: "#1a0a00",
    gradient: {
      type: "linear",
      angle: 160,
      stops: [
        { color: "#2c1810", position: 0 },
        { color: "#0f0705", position: 100 },
      ],
    },
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Inter Variable",
    fontSize: 68,
    fontWeight: 600,
    color: "#fafaf9",
    horizontalAlign: "center",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.45,
    letterSpacing: -0.3,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 17,
    color: "#f97316",
    superscript: true,
  },
  reference: {
    fontFamily: "Inter Variable",
    fontSize: 38,
    fontWeight: 500,
    color: "#fb923c",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 1,
    position: "below",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 60, right: 100, bottom: 60, left: 100 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 82,
    textAreaHeight: 78,
    referenceGap: 28,
  },
  transition: {
    type: "slide",
    duration: 450,
    easing: "ease-out",
    direction: "up",
  },
}

// Charis — elegant, soft, serif
const CHARIS: BroadcastTheme = {
  ...base,
  id: "builtin-charis",
  name: "Charis",
  background: {
    type: "gradient",
    color: "#1a1a2e",
    gradient: {
      type: "linear",
      angle: 135,
      stops: [
        { color: "#1a1a2e", position: 0 },
        { color: "#16213e", position: 100 },
      ],
    },
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Source Serif 4 Variable",
    fontSize: 66,
    fontWeight: 400,
    color: "#e8e0d8",
    horizontalAlign: "center",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.6,
    letterSpacing: 0.3,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 16,
    color: "#c9a8e8",
    superscript: true,
  },
  reference: {
    fontFamily: "Source Serif 4 Variable",
    fontSize: 34,
    fontWeight: 400,
    color: "#c9a8e8",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 2,
    position: "above",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 80, right: 120, bottom: 80, left: 120 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 75,
    textAreaHeight: 72,
    referenceGap: 30,
  },
  transition: {
    type: "fade",
    duration: 500,
    easing: "ease-in-out",
    direction: "up",
  },
}

// Logos — modern, clean, sans-serif
const LOGOS: BroadcastTheme = {
  ...base,
  id: "builtin-logos",
  name: "Logos",
  background: {
    type: "solid",
    color: "#111111",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Instrument Sans Variable",
    fontSize: 62,
    fontWeight: 400,
    color: "#f5f5f5",
    horizontalAlign: "left",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.55,
    letterSpacing: -0.2,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 15,
    color: "#6b7280",
    superscript: true,
  },
  reference: {
    fontFamily: "Instrument Sans Variable",
    fontSize: 30,
    fontWeight: 500,
    color: "#6b7280",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 3,
    position: "above",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 60, right: 100, bottom: 60, left: 100 },
    textAlign: "left",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 78,
    textAreaHeight: 75,
    referenceGap: 20,
  },
  transition: {
    type: "slide",
    duration: 350,
    easing: "ease-out",
    direction: "up",
  },
}

// Shalom — lower-third, muted, calm
const SHALOM: BroadcastTheme = {
  ...base,
  id: "builtin-shalom",
  name: "Shalom",
  background: {
    type: "transparent",
    color: "transparent",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: true,
    color: "#1e293b",
    opacity: 0.85,
    borderRadius: 8,
    padding: 24,
  },
  verseText: {
    fontFamily: "DM Sans Variable",
    fontSize: 48,
    fontWeight: 400,
    color: "#f1f5f9",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.5,
    letterSpacing: 0,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: false,
    fontSize: 12,
    color: "#94a3b8",
    superscript: true,
  },
  reference: {
    fontFamily: "DM Sans Variable",
    fontSize: 26,
    fontWeight: 500,
    color: "#94a3b8",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 0,
    position: "below",
  },
  layout: {
    anchor: "bottom-left",
    offsetX: 60,
    offsetY: -50,
    padding: { top: 20, right: 32, bottom: 20, left: 32 },
    textAlign: "left",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 55,
    textAreaHeight: 25,
    referenceGap: 12,
  },
  transition: {
    type: "slide",
    duration: 300,
    easing: "ease-out",
    direction: "up",
  },
}

export const BUILTIN_THEMES: BroadcastTheme[] = [
  KAIROS,
  DOXA,
  PNEUMA,
  RHEMA,
  CHARIS,
  LOGOS,
  SHALOM,
]
