import type { BroadcastTheme } from "@/types/broadcast"

const base: Omit<
  BroadcastTheme,
  "id" | "name" | "background" | "verseText" | "reference" | "layout" | "transition" | "textBox" | "verseNumbers"
> = {
  builtin: true,
  pinned: false,
  createdAt: 0,
  updatedAt: 0,
  resolution: { width: 1920, height: 1080 },
}

// ─── KAIROS ─────────────────────────────────────────
// Quiet confidence. Still, spacious, certain.
// Like a Kinfolk editorial — the verse breathes.
const KAIROS: BroadcastTheme = {
  ...base,
  id: "builtin-kairos",
  name: "Kairos",
  background: {
    type: "solid",
    color: "#f7f4ef",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Figtree Variable",
    fontSize: 62,
    fontWeight: 400,
    color: "#1a1814",
    horizontalAlign: "left",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.65,
    letterSpacing: -0.3,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 13,
    color: "#8b9a7d",
    superscript: true,
  },
  reference: {
    fontFamily: "Figtree Variable",
    fontSize: 26,
    fontWeight: 500,
    color: "#8b9a7d",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 5,
    position: "above",
  },
  layout: {
    anchor: "center",
    offsetX: -80,
    offsetY: 0,
    padding: { top: 100, right: 160, bottom: 100, left: 160 },
    textAlign: "left",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 68,
    textAreaHeight: 65,
    referenceGap: 28,
  },
  transition: {
    type: "fade",
    duration: 800,
    easing: "ease-out",
    direction: "up",
  },
}

// ─── DOXA ───────────────────────────────────────────
// Cinematic awe. Vast, gilded, ancient.
// Like gold leaf on a dark manuscript page.
const DOXA: BroadcastTheme = {
  ...base,
  id: "builtin-doxa",
  name: "Doxa",
  background: {
    type: "gradient",
    color: "#08080c",
    gradient: {
      type: "radial",
      angle: 0,
      stops: [
        { color: "#18161e", position: 0 },
        { color: "#08080c", position: 100 },
      ],
    },
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Literata Variable",
    fontSize: 70,
    fontWeight: 400,
    color: "#f0ebe0",
    horizontalAlign: "center",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.55,
    letterSpacing: 0.2,
    shadow: { color: "rgba(0,0,0,0.5)", blur: 20, x: 0, y: 6 },
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 17,
    color: "#c5a55a",
    superscript: true,
  },
  reference: {
    fontFamily: "Manrope Variable",
    fontSize: 28,
    fontWeight: 600,
    color: "#c5a55a",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 8,
    position: "above",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 10,
    padding: { top: 100, right: 120, bottom: 100, left: 120 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 75,
    textAreaHeight: 70,
    referenceGap: 40,
  },
  transition: {
    type: "fade",
    duration: 1000,
    easing: "ease-in-out",
    direction: "up",
  },
}

// ─── PNEUMA ─────────────────────────────────────────
// Contemporary warmth. Present, luminous, alive.
// Like a well-produced worship concert — text floats over content.
const PNEUMA: BroadcastTheme = {
  ...base,
  id: "builtin-pneuma",
  name: "Pneuma",
  background: {
    type: "transparent",
    color: "transparent",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: true,
    color: "#0d1117",
    opacity: 0.75,
    borderRadius: 10,
    padding: 32,
  },
  verseText: {
    fontFamily: "Manrope Variable",
    fontSize: 52,
    fontWeight: 500,
    color: "#f8f6f2",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.55,
    letterSpacing: -0.2,
    shadow: { color: "rgba(0,0,0,0.7)", blur: 8, x: 0, y: 2 },
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 14,
    color: "#e8a838",
    superscript: true,
  },
  reference: {
    fontFamily: "Manrope Variable",
    fontSize: 28,
    fontWeight: 600,
    color: "#e8a838",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 1,
    position: "below",
  },
  layout: {
    anchor: "bottom-center",
    offsetX: 0,
    offsetY: -48,
    padding: { top: 28, right: 44, bottom: 28, left: 44 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 88,
    textAreaHeight: 32,
    referenceGap: 18,
  },
  transition: {
    type: "slide",
    duration: 250,
    easing: "ease-out",
    direction: "up",
  },
}

// ─── RHEMA ──────────────────────────────────────────
// Bold + expressive. Fierce, grounded, burning.
// Like ember light on stone — the word hits hard.
const RHEMA: BroadcastTheme = {
  ...base,
  id: "builtin-rhema",
  name: "Rhema",
  background: {
    type: "gradient",
    color: "#080403",
    gradient: {
      type: "linear",
      angle: 155,
      stops: [
        { color: "#1c100a", position: 0 },
        { color: "#080403", position: 100 },
      ],
    },
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Bricolage Grotesque Variable",
    fontSize: 66,
    fontWeight: 700,
    color: "#fff5eb",
    horizontalAlign: "center",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.4,
    letterSpacing: -0.5,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 16,
    color: "#d4512a",
    superscript: true,
  },
  reference: {
    fontFamily: "Bricolage Grotesque Variable",
    fontSize: 34,
    fontWeight: 500,
    color: "#d4512a",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 2,
    position: "below",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 80, right: 100, bottom: 80, left: 100 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 78,
    textAreaHeight: 75,
    referenceGap: 32,
  },
  transition: {
    type: "slide",
    duration: 400,
    easing: "ease-out",
    direction: "up",
  },
}

// ─── CHARIS ─────────────────────────────────────────
// Sacred reverence. Gentle, deep, sacred.
// Like a illuminated manuscript in a quiet chapel.
const CHARIS: BroadcastTheme = {
  ...base,
  id: "builtin-charis",
  name: "Charis",
  background: {
    type: "gradient",
    color: "#0c0e1a",
    gradient: {
      type: "linear",
      angle: 140,
      stops: [
        { color: "#121428", position: 0 },
        { color: "#0a0b14", position: 100 },
      ],
    },
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Alegreya Variable",
    fontSize: 68,
    fontWeight: 400,
    color: "#e8e0d2",
    horizontalAlign: "center",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.6,
    letterSpacing: 0.3,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 16,
    color: "#9b8bb4",
    superscript: true,
  },
  reference: {
    fontFamily: "Alegreya Variable",
    fontSize: 32,
    fontWeight: 400,
    color: "#9b8bb4",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 3,
    position: "above",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 100, right: 140, bottom: 100, left: 140 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 70,
    textAreaHeight: 68,
    referenceGap: 34,
  },
  transition: {
    type: "fade",
    duration: 700,
    easing: "ease-in-out",
    direction: "up",
  },
}

// ─── LOGOS ───────────────────────────────────────────
// Refined + purposeful. Precise, honest, clear.
// Like a Swiss typography poster — nothing wasted.
const LOGOS: BroadcastTheme = {
  ...base,
  id: "builtin-logos",
  name: "Logos",
  background: {
    type: "solid",
    color: "#0e1012",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 60,
    fontWeight: 400,
    color: "#e8e8e8",
    horizontalAlign: "left",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.6,
    letterSpacing: -0.2,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 14,
    color: "#5a7080",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 24,
    fontWeight: 500,
    color: "#5a7080",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 6,
    position: "above",
  },
  layout: {
    anchor: "center",
    offsetX: -60,
    offsetY: 0,
    padding: { top: 80, right: 120, bottom: 80, left: 120 },
    textAlign: "left",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 72,
    textAreaHeight: 70,
    referenceGap: 22,
  },
  transition: {
    type: "fade",
    duration: 300,
    easing: "ease-out",
    direction: "up",
  },
}

// ─── SHALOM ─────────────────────────────────────────
// Warm + inviting. Soft, steady, near.
// Like a gentle hand on your shoulder — unobtrusive lower-third.
const SHALOM: BroadcastTheme = {
  ...base,
  id: "builtin-shalom",
  name: "Shalom",
  background: {
    type: "transparent",
    color: "transparent",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: true,
    color: "#1a2030",
    opacity: 0.88,
    borderRadius: 6,
    padding: 28,
  },
  verseText: {
    fontFamily: "Figtree Variable",
    fontSize: 44,
    fontWeight: 400,
    color: "#eae6df",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.55,
    letterSpacing: 0,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: false,
    fontSize: 11,
    color: "#7a8594",
    superscript: true,
  },
  reference: {
    fontFamily: "Figtree Variable",
    fontSize: 22,
    fontWeight: 500,
    color: "#7a8594",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 0.5,
    position: "below",
  },
  layout: {
    anchor: "bottom-left",
    offsetX: 64,
    offsetY: -56,
    padding: { top: 24, right: 36, bottom: 24, left: 36 },
    textAlign: "left",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 52,
    textAreaHeight: 24,
    referenceGap: 10,
  },
  transition: {
    type: "slide",
    duration: 300,
    easing: "ease-out",
    direction: "up",
  },
}

export const BUILTIN_THEMES: BroadcastTheme[] = [
  KAIROS,
  DOXA,
  PNEUMA,
  RHEMA,
  CHARIS,
  LOGOS,
  SHALOM,
]
